apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  {{- $files := .Files }}
  {{- range tuple "prometheus.rules" "prometheus.yml" }}
  {{ . }}: |-
{{ $files.Get . }}
  {{- end }}